### ISSUE TITLE
Sensor blocks-Ultrasonic sensor

### ISSUE THREAD

**Issue by rubeena1234** [kreativhut/z-blockly-tracker#139]
![image](https://user-images.githubusercontent.com/104137102/170470791-f1a3c055-fa34-421e-a52c-fd5c3ab08878.png)
Change the native code of the above sensor block as follows

Native code:
long readUltrasonicDistance(int triggerPin, int echoPin)
{
  pinMode(triggerPin, OUTPUT); 
  digitalWrite(triggerPin, LOW);
  delayMicroseconds(2);
  digitalWrite(triggerPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(triggerPin, LOW);
  pinMode(echoPin, INPUT);
  return pulseIn(echoPin, HIGH);
}

void setup()
{

}

void loop()
{
  0.01723 * readUltrasonicDistance(0, 0)
}

**Comment by rubeena1234** [comment]
I added the same as new issue thats why I closed it.

**Comment by kreativhut** [comment]
If a test is failed, comment below why the test is failed. If it is a
success, then close the issue

**Comment by rubeena1234** [comment]
okay!
