### ISSUE TITLE
Serial Monitor

### ISSUE THREAD

**Issue by rubeena1234** [kreativhut/z-blockly-tracker#160]
![image](https://user-images.githubusercontent.com/104137102/171107876-a3fb20be-778a-4bf4-880a-70d7bac91576.png)
 Add auto scroll and clear Output options to z blockly's serial monitor as shown in the above image.

**Comment by kreativhut** [comment]
I have adjusted the scrolling issue. But if it is not the indented behavior, describe the behavior.
@rubeena1234 @Maharajacentrado

**Comment by rubeena1234** [comment]
Instead of scrolling manually by clicking on the scrollbar it should automatically scroll and appear like it does in arduino IDE as shown in the given video.

https://drive.google.com/file/d/1ePy2pZowbEhG8E-HcoP2pO-syP3FzqUV/view?usp=sharing

**Comment by kreativhut** [comment]
This requires a design change in Serial Monitor. I will see what I can do
