### ISSUE TITLE
Block Loop 

### ISSUE THREAD

**Issue by Maharajacentrado** [kreativhut/z-blockly-tracker#164]
While block is not merging with other blocks 
eg: equals to block 
<img width="230" alt="image" src="https://user-images.githubusercontent.com/104857726/171176095-441dcd01-7974-4dcd-b347-c80e58db49de.png">

**Comment by kreativhut** [comment]
I have modified all the blocks in loop
FYI - @Maharajacentrado @roshan1centrado @rubeena1234

**Comment by rubeena1234** [comment]
I am still unable to place the equal to block inside the while block. Kindly check for all the other blocks.


![Image](https://user-images.githubusercontent.com/104137102/177098245-ea6c5b96-6b0f-460c-a9bf-869178fc0b9e.png)

**Comment by kreativhut** [comment]
@rubeena1234 You are not using the latest version. Please use v1.0.5

**Comment by roshan1centrado** [comment]
ok

**Comment by rubeena1234** [comment]
> @rubeena1234 You are not using the latest version. Please use v1.0.5

ok will check with the new version.
