### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by rubeena1234** [kreativhut/z-blockly-tracker#168]
https://drive.google.com/file/d/1SSCVhoUfBkTSLY8atc-X6Tsb-Mp7qjvj/view?usp=sharing

When I overlap the block it has to be deleted instead of going behind.

**Comment by kreativhut** [comment]
@rubeena1234, this feature cannot be fully implemented as blockly doesn't provide any change handlers when a block is disconnected.

But the way we have implemented a default block like text or number attached to other blocks can be modified.
I have implemented this feature in almost all the blocks that has default blocks attached to them. Try placing another block over them.

FYI - @Maharajacentrado @roshan1centrado @vigneshcentrado
