### ISSUE TITLE
 Block-Upper button pressed

### ISSUE THREAD

**Issue by rubeena1234** [kreativhut/z-blockly-tracker#214]
Kindly change the native code as given here.
### Block-Upper button pressed

<img width="154" alt="image" src="https://user-images.githubusercontent.com/104857726/171002065-9fd71a01-f6d0-424b-a3c3-632a827fc9d6.png">

Please change the block name as upper button pressed
### C++

```c++
void setup()
{
pinMode(23, INPUT);
}
void loop()
{
digitalRead(23);

}

```

_Originally posted by @Maharajacentrado in https://github.com/kreativhut/z-blockly-tracker/discussions/151#discussioncomment-2849099_

**Comment by kreativhut** [comment]
@rubeena1234 @Maharajacentrado @vigneshcentrado @roshan1centrado 
Please add `High Priority` label when it really is urgent. Because we have to pause our work on other tasks and focus on high priority.
