### ISSUE TITLE
Block error

### ISSUE THREAD

**Issue by rubeena1234** [kreativhut/z-blockly-tracker#236]
In the new version the blocks which were already working is not working now, if I duplicate the blocks it is not getting enabled, the changes made in the blocks are not getting updated in the text code, the number block is also not working correctly. Please check the screen recording given below.

https://drive.google.com/file/d/1bCAOXAkrrMaKzyGnxJDOe94CLmLbOtZs/view?usp=sharing

**Comment by kreativhut** [comment]
@rubeena1234 - This is issue is coming from Math Block. Close this issue and comment under the math block Issue https://github.com/kreativhut/z-blockly-tracker/issues/126
