### ISSUE TITLE
Block- GSM

### ISSUE THREAD

**Issue by Maharajacentrado** [kreativhut/z-blockly-tracker#299]
<img width="806" alt="image" src="https://user-images.githubusercontent.com/104857726/183578169-7f262880-b267-4d6f-84bb-7aabebc968e8.png">

(i) if I place the GSM block inside the if condition or inside void loop the code should appear inside it. 

(ii) if I place the two gsm blocks then the native code for last gsm code is appearing both should appear.

the following lines of code should change accordingly other lines are same: 

```
Serial.println("Initializing...");
    delay(1000);

    mySerial.println("AT"); //Handshaking with SIM900
    updateSerial();

    mySerial.println("AT+CMGF=1"); // Configuring TEXT mode
    updateSerial();
    mySerial.println("AT+CMGS=\"+918680925939\"");
    updateSerial();
    mySerial.print("\"Hello\""); //text content
    updateSerial();
    mySerial.write(26);
```

**Comment by kreativhut** [comment]
@Maharajacentrado - the code you have attached is for **send** - **sms** option right?

**Comment by Maharajacentrado** [comment]
yes the conditions should satisfy all the blocks. 

send sms
receive sms
send call 
receive sms

**Comment by kreativhut** [comment]
@Maharajacentrado - update the discussion and attach its link please
