### ISSUE TITLE
Block names to be changed

### ISSUE THREAD

**Issue by rubeena1234** [kreativhut/z-blockly-tracker#82]
### Discussed in https://github.com/kreativhut/z-blockly-tracker/discussions/81

<div type='discussions-op-text'>

<sup>Originally posted by **rubeena1234** May 19, 2022</sup>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/PRADEEP/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/PRADEEP/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Section | Existing name | New name
-- | -- | --
Logic | if do |  
  | if do else | if else
Text | to append text | to add text
Variable | Set constant which is   equivalent to | # define equivalent   to
I/O | measure…pulse on   pin#...(timeout after ms) | measure…pulse on   pin#...(timeout)
LED | RGB LED   pin:WS2812-RGB LED | RGB LED pin:   NeoPixel-RGB LED
  | WS2812-RGB LED Port:   Brightness  Number | NeoPixel RGB LED   Port: Brightness  Number
  | WS2812-RGB LED Port:   Position Colour | Neopixel RGB LED   Port: Position Colour
Serial | Software Serial   TX  RX    Baudios | Software Serial   TX  RX    Baudrate
RF-&-TF | Initialize the radio   receiver PIN | Initialize the RF   receiver at PIN
  | Initialize the radio   Transmitter PIN | Initialize the RF   Transmitter PIN
  | Define the message to   send Message | Message to be sent
Keypad | Get pressed key on   keypad | Get key pressed on   keypad

</body>

</html>
</div>

**Comment by kreativhut** [comment]
Closing this issue  as it is on the board for too long
